worker:
  build: .
  environment:
    GK_CONFIG_REDIS_HOST: 'redis'
    GK_BROKER_URL: 'redis://redis:6379/0'
    GK_CELERY_RESULT_BACKEND: 'redis://redis:6379/0'
    GK_PHANTOM_SERVER: 'http://192.168.99.100:5000/'
    GK_CELERYD_CONCURRENCY: 1
  links:
    - redis
  command: worker

cookie_worker:
  build: .
  environment:
    GK_CONFIG_REDIS_HOST: 'redis'
    GK_BROKER_URL: 'redis://redis:6379/0'
    GK_CELERY_RESULT_BACKEND: 'redis://redis:6379/0'
    GK_PHANTOM_SERVER: 'http://192.168.99.100:5000/'
  links:
    - redis
  command: cookie_worker

beat:
  build: .
  environment:
    GK_CONFIG_REDIS_HOST: 'redis'
    GK_BROKER_URL: 'redis://redis:6379/0'
    GK_CELERY_RESULT_BACKEND: 'redis://redis:6379/0'
    GK_PHANTOM_SERVER: 'http://192.168.99.100:5000/'
  links:
    - redis
  command: beat

flower:
  build: .
  ports:
    - "192.168.99.100:5555:5000"
  environment:
    GK_CONFIG_REDIS_HOST: 'redis'
    GK_BROKER_URL: 'redis://redis:6379/0'
    GK_CELERY_RESULT_BACKEND: 'redis://redis:6379/0'
    GK_PHANTOM_SERVER: 'http://192.168.99.100:5000/'
  links:
    - redis
  command: flower

redis:
  image: redis
